export const types = {
  authCheckingFinish: "[auth] Checking login state",
  authStartLogin: "[auth] Start Login",
  authLogin: "[auth] login",
  authStartRegister: "[auth] Start Register",
  authStartTokenRenew: "[auth] Start Token renew",
  authLogout: "[auth] Logout",
  login: "[Auth] Login",

  inscripcionGetAsginaturas: "[Incripcion] obtener asignaturas ",
  inscripcionStartChecking: "[Incripcion] start checking ",
  inscripcionObetenerMalla: "[Incripcion] obtener malla ",
  incripcionActiva: "[Incripcion] activa",
  inscribirAsignaturas: "[Incripcion} inscribir asignatura",
  inscripcionEliminarAsingatura: "[Incripcion] eliminar de la inscripcion",
  inscripcionObetenrIncripcion: "[Incripcion] obtener inscripcion",
  incripcionHorario: "[Incripcion] añadir horario",
  incripcionReahacer: "[Incripcion] reahacer",

  adminGetFacultades: "[Admin] get Facultades ",
  adminSetOption: "[Admin] set Option",
  adminGetAsignaturas: "[Admin] get Asignaturas",
  adminActiveAsignatura: "[Admin] active asignautra",
  adminOfertaAcademicaSetFacultad: "[Admin] oferta academica set facultad",
  adminOfertaAcademicaSetCarrera: "[Admin] oferta academica set carrera",
  adminOfertaAcademicaSetAsignatura: "[Admin] oferta academica set asignatura",
  adminOfertaAcademicaAddSeccion: "[Admin] oferta academica add sección",
  adminLimpearOfertaAcademica: "[Admin] Limpiar oferta academica asignatura",
  adminCrearOfertaAcademica: "[Admin] crear oferta academica",
};
